title: Izadora Lima
description: Game & Narrative Designer
author: Izadora Lima
logo: /doraiza.github.io/static/img/avatar.png
github: https://github.com/doraiza
about: Game & Narrative Designer

baseurl: ""
url: "http://doraiza.github.io"

allowsearch: false

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \desmyeolada
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
